import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob
import argparse
import sys
from pathlib import Path
import re


def plot_epoch(path_csv: str, path_plot: str, ax_aggr=None,
               plot_olap=False) -> None:
    data = pd.read_csv(path_csv)
    epoch = data['Epoch'][0]
    data_x = data['Point']
    data_y = data['MatchMass'] * 100.0 / data['TotalMass']
    fig, ax = plt.subplots(1, 1)
    ax.plot(data_x, data_y, label='Epoch {0}: Overlap %'.format(epoch))

    if ax_aggr:
        ax_aggr.plot(data_x, data_y, label='Epoch {0}: Overlap %'.format(epoch))

    if plot_olap:
        ax2 = ax.twinx()
        data_olap = data['MatchCount']
        ax2.plot(data_x, data_olap,
                 label='Epoch {0}: Overlap Count'.format(epoch))

    ax.set_xlabel('Attribute Range')
    ax.set_ylabel('Overlap Percent')
    ax.set_title('Manifest Stats for Epoch {0}'.format(epoch))

    # fig.show()
    fig.savefig(path_plot, dpi=300)


def run(path_in: str, path_out: str) -> None:
    manifest_files = glob.glob(path_in + '/manifest.e*.csv')
    print('{0} files found'.format(len(manifest_files)))
    manifest_files.sort()

    fig_aggr, ax_aggr = plt.subplots(1, 1)

    for fin in manifest_files:
        print('Plotting {0}'.format(fin))
        fout = re.sub('csv$', 'pdf', Path(fin).name)
        fout = Path(path_out) / fout
        plot_epoch(fin, fout, ax_aggr=ax_aggr)

    ax_aggr.set_xlabel('Attribute Range')
    ax_aggr.set_ylabel('Overlap Percent')
    ax_aggr.set_title('Aggregate Manifest Stats')
    ax_aggr.legend()

    # fig_aggr.show()
    aggr_out = Path(path_out) / 'manifest.aggr.pdf'
    fig_aggr.savefig(aggr_out, dpi=300)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog='Manifest Plotter',
        description='''
        Plot manifest CSVs generated by the RDB reader''',
        epilog='''
        TBD
        '''
    )

    parser.add_argument('--input-path', '-i', type=str,
                        help='Path to CSV input files', required=True)
    parser.add_argument('--output-path', '-o', type=str,
                        help='Destination for plotted graphs', required=True)

    options = parser.parse_args()
    if not options.input_path or not options.output_path:
        parser.print_help()
        sys.exit(0)

    run(options.input_path, options.output_path)
